services:
  - type: web
    name: my-app
    staticPublishPath: dist
    buildCommand: npm install && npm run build
    envVars:
      - key: VITE_BACKEND_BASE_URL
        value: https://whatsappclone-7ggl.onrender.co
